runners:
  self-hosted-ubuntu-22.04-x86-64:
    # A range from lowest to highest
    cpu: [16, 64]
    ram: [64, 192]
    disk: default
    family: ["c7", "m7", "r7"]
    # Don't allow runner interruption
    spot: false
    # Prefer instances with high capacity (low interruption risk), then low cost
    #spot: capacity-optimized
    image: ubuntu22-full-x64
# Give runner SSH access to the GitHub SSH keys of these accounts
admins:
  - jfrank-summit
  - teor2345
  - vedhavyas
