
//! Autogenerated weights for `balance_transfer_check_extension`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 46.2.0
//! DATE: 2025-07-11, STEPS: `250`, REPEAT: `100`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `protocol-team-testing`, CPU: `AMD Ryzen 5 3600 6-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/production/subspace-node
// benchmark
// pallet
// --runtime=./target/production/wbuild/subspace-runtime/subspace_runtime.compact.compressed.wasm
// --extrinsic=*
// --wasm-execution=compiled
// --genesis-builder=none
// --steps=250
// --repeat=100
// --heap-pages=4096
// --pallet=balance_transfer_check_extension
// --output=./crates/subspace-runtime-primitives/src/weights/balance_transfer_check_extension.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `balance_transfer_check_extension`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::extension::WeightInfo for WeightInfo<T> {
	/// Storage: `RuntimeConfigs::EnableBalanceTransfers` (r:1 w:0)
	/// Proof: `RuntimeConfigs::EnableBalanceTransfers` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 5000]`.
	fn balance_transfer_check_multiple(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `1486`
		// Minimum execution time: 1_280_000 picoseconds.
		Weight::from_parts(1_406_119, 0)
			.saturating_add(Weight::from_parts(0, 1486))
			// Standard Error: 0
			.saturating_add(Weight::from_parts(5, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `RuntimeConfigs::EnableBalanceTransfers` (r:1 w:0)
	/// Proof: `RuntimeConfigs::EnableBalanceTransfers` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 5000]`.
	fn balance_transfer_check_utility(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `1486`
		// Minimum execution time: 1_299_000 picoseconds.
		Weight::from_parts(1_401_176, 0)
			.saturating_add(Weight::from_parts(0, 1486))
			// Standard Error: 0
			.saturating_add(Weight::from_parts(12, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	/// Storage: `RuntimeConfigs::EnableBalanceTransfers` (r:1 w:0)
	/// Proof: `RuntimeConfigs::EnableBalanceTransfers` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[0, 5000]`.
	fn balance_transfer_check_multisig(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `1486`
		// Minimum execution time: 1_290_000 picoseconds.
		Weight::from_parts(1_413_516, 0)
			.saturating_add(Weight::from_parts(0, 1486))
			// Standard Error: 0
			.saturating_add(Weight::from_parts(6, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(1))
	}
}
