FROM ubuntu:20.04

ARG RUSTC_VERSION=nightly

WORKDIR /code

RUN \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        git \
        llvm \
        clang && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain $RUSTC_VERSION

RUN /root/.cargo/bin/rustup target add wasm32-unknown-unknown

COPY Cargo.lock /code/Cargo.lock
COPY Cargo.toml /code/Cargo.toml

# Just enough files for `git rev-parse --short HEAD` to work (used in Substrate node build)
COPY .git /code/.git
# Just an empty directory for Git to recognize it is indeed a Git repository
RUN mkdir /code/.git/objects
COPY crates /code/crates
COPY cumulus /code/cumulus
COPY polkadot /code/polkadot
COPY substrate /code/substrate

# Up until this line all Rust images in this repo should be the same to share the same layers

RUN \
    /root/.cargo/bin/cargo build --release --bin subspace-node && \
    mv target/release/subspace-node subspace-node && \
    rm -rf target

FROM ubuntu:20.04

RUN \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY --from=0 /code/subspace-node /subspace-node

RUN mkdir /var/subspace && chown nobody:nogroup /var/subspace

VOLUME /var/subspace

USER nobody:nogroup

ENTRYPOINT ["/subspace-node"]
