FROM ubuntu:20.04

WORKDIR /code

RUN \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        gcc \
        llvm \
        clang && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly

COPY Cargo.lock /code/Cargo.lock
COPY Cargo.toml /code/Cargo.toml

COPY crates /code/crates
COPY substrate /code/substrate
COPY node-template-subspace /code/node-template-subspace

RUN \
    /root/.cargo/bin/cargo build --release --bin subspace-farmer && \
    mv target/release/subspace-farmer subspace-farmer && \
    rm -rf target

FROM ubuntu:20.04

COPY --from=0 /code/subspace-farmer /subspace-farmer

ENV SUBSAPCE_DIR=/var/subspace

RUN mkdir /var/subspace && chown nobody:nogroup /var/subspace

VOLUME /var/subspace

USER nobody:nogroup

ENTRYPOINT ["/subspace-farmer"]
