FROM ubuntu:20.04

ARG RUSTC_VERSION=nightly-2022-05-16
ARG PROFILE=production
ARG RUSTFLAGS
# Workaround for https://github.com/rust-lang/cargo/issues/10583
ENV CARGO_NET_GIT_FETCH_WITH_CLI=true
# Incremental compilation here isn't helpful
ENV CARGO_INCREMENTAL=0

WORKDIR /code

RUN \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        git \
        llvm \
        clang \
        cmake \
        make && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain $RUSTC_VERSION

RUN /root/.cargo/bin/rustup target add wasm32-unknown-unknown

COPY Cargo.lock /code/Cargo.lock
COPY Cargo.toml /code/Cargo.toml
COPY rust-toolchain.toml /code/rust-toolchain.toml

COPY crates /code/crates
COPY cumulus /code/cumulus
COPY orml /code/orml
COPY substrate /code/substrate
COPY test /code/test

# Up until this line all Rust images in this repo should be the same to share the same layers

ARG SUBSTRATE_CLI_GIT_COMMIT_HASH

RUN \
    /root/.cargo/bin/cargo build \
        -Z build-std \
        --profile $PROFILE \
        --bin subspace-node \
        --target x86_64-unknown-linux-gnu && \
    mv target/*/*/subspace-node subspace-node && \
    rm -rf target

FROM ubuntu:20.04

RUN \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ca-certificates curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

HEALTHCHECK CMD curl \
                  -H "Content-Type: application/json" \
                  -d '{ "id": 1, "jsonrpc": "2.0", "method": "system_health", "params": [] }' \
                  -f "http://localhost:9933"

COPY --from=0 /code/subspace-node /subspace-node

RUN mkdir /var/subspace && chown nobody:nogroup /var/subspace

VOLUME /var/subspace

USER nobody:nogroup

ENTRYPOINT ["/subspace-node"]
