# This wildcard allows to merge whatever user might have configured in their home folder
[target.'cfg(all())']
# TODO: `-Znext-solver=globally` is a requirement for `generic_const_args`, `-Zmin-recursion-limit=256` is in turn
#  needed for some crates due to `-Znext-solver=globally`
rustflags = ["-Znext-solver=globally", "-Zmin-recursion-limit=256"]
rustdocflags = ["-Znext-solver=globally", "-Zmin-recursion-limit=256"]
