
//! Autogenerated weights for `pallet_domains`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 46.2.0
//! DATE: 2025-09-30, STEPS: `2`, REPEAT: `1`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `macmini`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/release/subspace-node
// benchmark
// pallet
// --runtime=./target/release/wbuild/subspace-runtime/subspace_runtime.compact.compressed.wasm
// --genesis-builder=none
// --steps=2
// --repeat=1
// --pallet=pallet_domains
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./crates/pallet-domains/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_domains`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
	/// Storage: `Domains::HeadReceiptNumber` (r:1 w:1)
	/// Proof: `Domains::HeadReceiptNumber` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::NewAddedHeadReceipt` (r:1 w:1)
	/// Proof: `Domains::NewAddedHeadReceipt` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LatestConfirmedDomainExecutionReceipt` (r:1 w:1)
	/// Proof: `Domains::LatestConfirmedDomainExecutionReceipt` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::ExecutionInbox` (r:4 w:1)
	/// Proof: `Domains::ExecutionInbox` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::PendingSlashes` (r:1 w:0)
	/// Proof: `Domains::PendingSlashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::InvalidBundleAuthors` (r:1 w:1)
	/// Proof: `Domains::InvalidBundleAuthors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainStakingSummary` (r:1 w:1)
	/// Proof: `Domains::DomainStakingSummary` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::BlockTree` (r:2 w:2)
	/// Proof: `Domains::BlockTree` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `RuntimeConfigs::DomainBlockPruningDepth` (r:1 w:0)
	/// Proof: `RuntimeConfigs::DomainBlockPruningDepth` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Domains::BlockTreeNodes` (r:1 w:2)
	/// Proof: `Domains::BlockTreeNodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LatestSubmittedER` (r:1 w:0)
	/// Proof: `Domains::LatestSubmittedER` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Transporter::DomainBalances` (r:1 w:1)
	/// Proof: `Transporter::DomainBalances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainRegistry` (r:1 w:0)
	/// Proof: `Domains::DomainRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainRuntimeUpgradeRecords` (r:1 w:0)
	/// Proof: `Domains::DomainRuntimeUpgradeRecords` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::SuccessfulBundles` (r:1 w:1)
	/// Proof: `Domains::SuccessfulBundles` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::HeadDomainNumber` (r:1 w:1)
	/// Proof: `Domains::HeadDomainNumber` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::OperatorBundleSlot` (r:1 w:1)
	/// Proof: `Domains::OperatorBundleSlot` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::InboxedBundleAuthor` (r:0 w:1)
	/// Proof: `Domains::InboxedBundleAuthor` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::ConsensusBlockHash` (r:0 w:1)
	/// Proof: `Domains::ConsensusBlockHash` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_bundle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1896`
		//  Estimated: `12786`
		// Minimum execution time: 134_000_000 picoseconds.
		Weight::from_parts(134_000_000, 0)
			.saturating_add(Weight::from_parts(0, 12786))
			.saturating_add(T::DbWeight::get().reads(21))
			.saturating_add(T::DbWeight::get().writes(16))
	}
	/// Storage: `Domains::HeadReceiptNumber` (r:1 w:1)
	/// Proof: `Domains::HeadReceiptNumber` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::BlockTreeNodes` (r:1 w:0)
	/// Proof: `Domains::BlockTreeNodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_fraud_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1092`
		//  Estimated: `4557`
		// Minimum execution time: 29_000_000 picoseconds.
		Weight::from_parts(29_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4557))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Domains::BlockTree` (r:1 w:1)
	/// Proof: `Domains::BlockTree` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::BlockTreeNodes` (r:1 w:1)
	/// Proof: `Domains::BlockTreeNodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LatestSubmittedER` (r:100 w:0)
	/// Proof: `Domains::LatestSubmittedER` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::Operators` (r:100 w:100)
	/// Proof: `Domains::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::PendingSlashes` (r:1 w:1)
	/// Proof: `Domains::PendingSlashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainStakingSummary` (r:1 w:1)
	/// Proof: `Domains::DomainStakingSummary` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 100]`.
	fn handle_bad_receipt(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `983 + n * (192 ±0)`
		//  Estimated: `268718`
		// Minimum execution time: 45_000_000 picoseconds.
		Weight::from_parts(1_600_000_000, 0)
			.saturating_add(Weight::from_parts(0, 268718))
			.saturating_add(T::DbWeight::get().reads(204))
			.saturating_add(T::DbWeight::get().writes(104))
	}
	/// Storage: `Domains::Operators` (r:200 w:100)
	/// Proof: `Domains::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:100 w:100)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Domains::DomainStakingSummary` (r:1 w:1)
	/// Proof: `Domains::DomainStakingSummary` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::PendingSlashes` (r:1 w:1)
	/// Proof: `Domains::PendingSlashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 100]`.
	/// The range of component `s` is `[0, 100]`.
	fn confirm_domain_block(n: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + n * (384 ±0) + s * (225 ±0)`
		//  Estimated: `270413 + n * (2603 ±0) + s * (1077 ±0)`
		// Minimum execution time: 1_450_000_000 picoseconds.
		Weight::from_parts(1_450_000_000, 0)
			.saturating_add(Weight::from_parts(0, 270413))
			// Standard Error: 8_260_225
			.saturating_add(Weight::from_parts(14_950_586, 0).saturating_mul(n.into()))
			// Standard Error: 8_260_362
			.saturating_add(Weight::from_parts(9_386_440, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(s.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
			.saturating_add(Weight::from_parts(0, 2603).saturating_mul(n.into()))
			.saturating_add(Weight::from_parts(0, 1077).saturating_mul(s.into()))
	}
	/// Storage: `Domains::DomainStakingSummary` (r:1 w:1)
	/// Proof: `Domains::DomainStakingSummary` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainChainRewards` (r:1 w:0)
	/// Proof: `Domains::DomainChainRewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::Operators` (r:100 w:100)
	/// Proof: `Domains::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LatestSubmittedER` (r:100 w:0)
	/// Proof: `Domains::LatestSubmittedER` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[1, 100]`.
	fn operator_reward_tax_and_restake(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `447 + n * (208 ±0)`
		//  Estimated: `269781`
		// Minimum execution time: 21_000_000 picoseconds.
		Weight::from_parts(486_000_000, 0)
			.saturating_add(Weight::from_parts(0, 269781))
			.saturating_add(T::DbWeight::get().reads(202))
			.saturating_add(T::DbWeight::get().writes(101))
	}
	/// Storage: `Domains::PendingSlashes` (r:1 w:1)
	/// Proof: `Domains::PendingSlashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainStakingSummary` (r:1 w:0)
	/// Proof: `Domains::DomainStakingSummary` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::Operators` (r:1 w:1)
	/// Proof: `Domains::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::Deposits` (r:11 w:10)
	/// Proof: `Domains::Deposits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DepositOnHold` (r:10 w:10)
	/// Proof: `Domains::DepositOnHold` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::OperatorEpochSharePrice` (r:2 w:2)
	/// Proof: `Domains::OperatorEpochSharePrice` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::Withdrawals` (r:11 w:0)
	/// Proof: `Domains::Withdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:10 w:10)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:12 w:12)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Domains::OperatorHighestSlot` (r:0 w:1)
	/// Proof: `Domains::OperatorHighestSlot` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::OperatorIdOwner` (r:0 w:1)
	/// Proof: `Domains::OperatorIdOwner` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `n` is `[0, 9]`.
	fn slash_operator(_n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1281 + n * (347 ±0)`
		//  Estimated: `32623`
		// Minimum execution time: 167_000_000 picoseconds.
		Weight::from_parts(777_000_000, 0)
			.saturating_add(Weight::from_parts(0, 32623))
			.saturating_add(T::DbWeight::get().reads(59))
			.saturating_add(T::DbWeight::get().writes(48))
	}
	/// Storage: `Domains::DomainStakingSummary` (r:1 w:1)
	/// Proof: `Domains::DomainStakingSummary` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LatestSubmittedER` (r:512 w:0)
	/// Proof: `Domains::LatestSubmittedER` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::Operators` (r:512 w:512)
	/// Proof: `Domains::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::InvalidBundleAuthors` (r:1 w:0)
	/// Proof: `Domains::InvalidBundleAuthors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DeregisteredOperators` (r:1 w:0)
	/// Proof: `Domains::DeregisteredOperators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DeactivatedOperators` (r:1 w:0)
	/// Proof: `Domains::DeactivatedOperators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LastEpochStakingDistribution` (r:0 w:1)
	/// Proof: `Domains::LastEpochStakingDistribution` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::OperatorEpochSharePrice` (r:0 w:512)
	/// Proof: `Domains::OperatorEpochSharePrice` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `p` is `[0, 512]`.
	fn finalize_domain_epoch_staking(_p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `108058`
		//  Estimated: `1376248`
		// Minimum execution time: 3_041_000_000 picoseconds.
		Weight::from_parts(4_445_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1376248))
			.saturating_add(T::DbWeight::get().reads(1028))
			.saturating_add(T::DbWeight::get().writes(1026))
	}
	/// Storage: `Domains::NextRuntimeId` (r:1 w:1)
	/// Proof: `Domains::NextRuntimeId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::RuntimeRegistry` (r:0 w:1)
	/// Proof: `Domains::RuntimeRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_domain_runtime() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `1485`
		// Minimum execution time: 19_963_000_000 picoseconds.
		Weight::from_parts(19_963_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1485))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Domains::RuntimeRegistry` (r:1 w:0)
	/// Proof: `Domains::RuntimeRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::ScheduledRuntimeUpgrades` (r:1 w:1)
	/// Proof: `Domains::ScheduledRuntimeUpgrades` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn upgrade_domain_runtime() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2481066`
		//  Estimated: `2484531`
		// Minimum execution time: 20_723_000_000 picoseconds.
		Weight::from_parts(20_723_000_000, 0)
			.saturating_add(Weight::from_parts(0, 2484531))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Domains::PermissionedActionAllowedBy` (r:1 w:0)
	/// Proof: `Domains::PermissionedActionAllowedBy` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::RuntimeRegistry` (r:1 w:1)
	/// Proof: `Domains::RuntimeRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Domains::NextDomainId` (r:1 w:1)
	/// Proof: `Domains::NextDomainId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::EvmChainIds` (r:1 w:1)
	/// Proof: `Domains::EvmChainIds` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Transporter::DomainBalances` (r:1 w:1)
	/// Proof: `Transporter::DomainBalances` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Domains::DomainSudoCalls` (r:0 w:1)
	/// Proof: `Domains::DomainSudoCalls` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainRegistry` (r:0 w:1)
	/// Proof: `Domains::DomainRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::BlockTreeNodes` (r:0 w:1)
	/// Proof: `Domains::BlockTreeNodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainStakingSummary` (r:0 w:1)
	/// Proof: `Domains::DomainStakingSummary` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LatestConfirmedDomainExecutionReceipt` (r:0 w:1)
	/// Proof: `Domains::LatestConfirmedDomainExecutionReceipt` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainGenesisBlockExecutionReceipt` (r:0 w:1)
	/// Proof: `Domains::DomainGenesisBlockExecutionReceipt` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::BlockTree` (r:0 w:1)
	/// Proof: `Domains::BlockTree` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Messenger::DomainChainAllowlistUpdate` (r:0 w:1)
	/// Proof: `Messenger::DomainChainAllowlistUpdate` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn instantiate_domain() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2481138`
		//  Estimated: `2484603`
		// Minimum execution time: 5_434_000_000 picoseconds.
		Weight::from_parts(5_434_000_000, 0)
			.saturating_add(Weight::from_parts(0, 2484603))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(14))
	}
	/// Storage: `Domains::PendingStakingOperationCount` (r:1 w:1)
	/// Proof: `Domains::PendingStakingOperationCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainStakingSummary` (r:1 w:1)
	/// Proof: `Domains::DomainStakingSummary` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainRegistry` (r:1 w:0)
	/// Proof: `Domains::DomainRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::NextOperatorId` (r:1 w:1)
	/// Proof: `Domains::NextOperatorId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Domains::DepositOnHold` (r:1 w:1)
	/// Proof: `Domains::DepositOnHold` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Domains::Deposits` (r:1 w:1)
	/// Proof: `Domains::Deposits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainChainRewards` (r:1 w:0)
	/// Proof: `Domains::DomainChainRewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LatestSubmittedER` (r:1 w:0)
	/// Proof: `Domains::LatestSubmittedER` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::InvalidBundleAuthors` (r:1 w:0)
	/// Proof: `Domains::InvalidBundleAuthors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DeregisteredOperators` (r:1 w:0)
	/// Proof: `Domains::DeregisteredOperators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DeactivatedOperators` (r:1 w:0)
	/// Proof: `Domains::DeactivatedOperators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::Operators` (r:0 w:1)
	/// Proof: `Domains::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LastEpochStakingDistribution` (r:0 w:1)
	/// Proof: `Domains::LastEpochStakingDistribution` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::OperatorIdOwner` (r:0 w:1)
	/// Proof: `Domains::OperatorIdOwner` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::OperatorEpochSharePrice` (r:0 w:1)
	/// Proof: `Domains::OperatorEpochSharePrice` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_operator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `684`
		//  Estimated: `6196`
		// Minimum execution time: 149_000_000 picoseconds.
		Weight::from_parts(149_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(14))
			.saturating_add(T::DbWeight::get().writes(12))
	}
	/// Storage: `Domains::Operators` (r:1 w:1)
	/// Proof: `Domains::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LatestSubmittedER` (r:1 w:0)
	/// Proof: `Domains::LatestSubmittedER` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::PendingStakingOperationCount` (r:1 w:1)
	/// Proof: `Domains::PendingStakingOperationCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainStakingSummary` (r:1 w:0)
	/// Proof: `Domains::DomainStakingSummary` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Domains::DepositOnHold` (r:1 w:1)
	/// Proof: `Domains::DepositOnHold` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Domains::Deposits` (r:1 w:1)
	/// Proof: `Domains::Deposits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::OperatorEpochSharePrice` (r:1 w:0)
	/// Proof: `Domains::OperatorEpochSharePrice` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn nominate_operator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1248`
		//  Estimated: `6196`
		// Minimum execution time: 122_000_000 picoseconds.
		Weight::from_parts(122_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `Domains::OperatorIdOwner` (r:1 w:0)
	/// Proof: `Domains::OperatorIdOwner` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::Operators` (r:1 w:1)
	/// Proof: `Domains::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LatestSubmittedER` (r:1 w:0)
	/// Proof: `Domains::LatestSubmittedER` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainStakingSummary` (r:1 w:1)
	/// Proof: `Domains::DomainStakingSummary` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::HeadDomainNumber` (r:1 w:0)
	/// Proof: `Domains::HeadDomainNumber` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `RuntimeConfigs::StakingWithdrawalPeriod` (r:1 w:0)
	/// Proof: `RuntimeConfigs::StakingWithdrawalPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Domains::DeregisteredOperators` (r:1 w:1)
	/// Proof: `Domains::DeregisteredOperators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn deregister_operator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `698`
		//  Estimated: `4163`
		// Minimum execution time: 38_000_000 picoseconds.
		Weight::from_parts(38_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4163))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Domains::Operators` (r:1 w:1)
	/// Proof: `Domains::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LatestSubmittedER` (r:1 w:0)
	/// Proof: `Domains::LatestSubmittedER` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::PendingStakingOperationCount` (r:1 w:1)
	/// Proof: `Domains::PendingStakingOperationCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainStakingSummary` (r:1 w:0)
	/// Proof: `Domains::DomainStakingSummary` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::Deposits` (r:1 w:1)
	/// Proof: `Domains::Deposits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::OperatorEpochSharePrice` (r:1 w:0)
	/// Proof: `Domains::OperatorEpochSharePrice` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::Withdrawals` (r:1 w:1)
	/// Proof: `Domains::Withdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::OperatorIdOwner` (r:1 w:0)
	/// Proof: `Domains::OperatorIdOwner` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Domains::HeadDomainNumber` (r:1 w:0)
	/// Proof: `Domains::HeadDomainNumber` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `RuntimeConfigs::StakingWithdrawalPeriod` (r:1 w:0)
	/// Proof: `RuntimeConfigs::StakingWithdrawalPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn withdraw_stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1442`
		//  Estimated: `6196`
		// Minimum execution time: 104_000_000 picoseconds.
		Weight::from_parts(104_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `Domains::Operators` (r:1 w:0)
	/// Proof: `Domains::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LatestSubmittedER` (r:1 w:0)
	/// Proof: `Domains::LatestSubmittedER` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainStakingSummary` (r:1 w:0)
	/// Proof: `Domains::DomainStakingSummary` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::Withdrawals` (r:1 w:1)
	/// Proof: `Domains::Withdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::HeadDomainNumber` (r:1 w:0)
	/// Proof: `Domains::HeadDomainNumber` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DepositOnHold` (r:1 w:1)
	/// Proof: `Domains::DepositOnHold` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Domains::Deposits` (r:1 w:1)
	/// Proof: `Domains::Deposits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `w` is `[1, 32]`.
	fn unlock_funds(_w: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1178 + w * (36 ±0)`
		//  Estimated: `5795`
		// Minimum execution time: 103_000_000 picoseconds.
		Weight::from_parts(104_000_000, 0)
			.saturating_add(Weight::from_parts(0, 5795))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `Domains::Operators` (r:1 w:1)
	/// Proof: `Domains::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LatestSubmittedER` (r:1 w:0)
	/// Proof: `Domains::LatestSubmittedER` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::HeadDomainNumber` (r:1 w:0)
	/// Proof: `Domains::HeadDomainNumber` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainStakingSummary` (r:1 w:0)
	/// Proof: `Domains::DomainStakingSummary` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:3 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Domains::Deposits` (r:2 w:1)
	/// Proof: `Domains::Deposits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::OperatorEpochSharePrice` (r:1 w:1)
	/// Proof: `Domains::OperatorEpochSharePrice` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::Withdrawals` (r:2 w:0)
	/// Proof: `Domains::Withdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DepositOnHold` (r:1 w:1)
	/// Proof: `Domains::DepositOnHold` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Domains::OperatorHighestSlot` (r:0 w:1)
	/// Proof: `Domains::OperatorHighestSlot` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::OperatorIdOwner` (r:0 w:1)
	/// Proof: `Domains::OperatorIdOwner` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn unlock_nominator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1349`
		//  Estimated: `8799`
		// Minimum execution time: 201_000_000 picoseconds.
		Weight::from_parts(201_000_000, 0)
			.saturating_add(Weight::from_parts(0, 8799))
			.saturating_add(T::DbWeight::get().reads(14))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	/// Storage: `Domains::DomainRegistry` (r:1 w:1)
	/// Proof: `Domains::DomainRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_domain_operator_allow_list() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `513`
		//  Estimated: `3978`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(25_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3978))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn transfer_treasury_funds() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `52`
		//  Estimated: `6196`
		// Minimum execution time: 43_000_000 picoseconds.
		Weight::from_parts(43_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Domains::HeadReceiptNumber` (r:1 w:1)
	/// Proof: `Domains::HeadReceiptNumber` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::NewAddedHeadReceipt` (r:1 w:1)
	/// Proof: `Domains::NewAddedHeadReceipt` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LatestConfirmedDomainExecutionReceipt` (r:1 w:0)
	/// Proof: `Domains::LatestConfirmedDomainExecutionReceipt` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::ExecutionInbox` (r:1 w:0)
	/// Proof: `Domains::ExecutionInbox` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::PendingSlashes` (r:1 w:0)
	/// Proof: `Domains::PendingSlashes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::InvalidBundleAuthors` (r:1 w:1)
	/// Proof: `Domains::InvalidBundleAuthors` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainStakingSummary` (r:1 w:1)
	/// Proof: `Domains::DomainStakingSummary` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::BlockTree` (r:1 w:1)
	/// Proof: `Domains::BlockTree` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `RuntimeConfigs::DomainBlockPruningDepth` (r:1 w:0)
	/// Proof: `RuntimeConfigs::DomainBlockPruningDepth` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Domains::LatestSubmittedER` (r:1 w:1)
	/// Proof: `Domains::LatestSubmittedER` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::BlockTreeNodes` (r:0 w:1)
	/// Proof: `Domains::BlockTreeNodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_receipt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `773`
		//  Estimated: `4238`
		// Minimum execution time: 59_000_000 picoseconds.
		Weight::from_parts(59_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4238))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `Domains::PreviousBundleAndExecutionReceiptVersions` (r:1 w:0)
	/// Proof: `Domains::PreviousBundleAndExecutionReceiptVersions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainRegistry` (r:1 w:0)
	/// Proof: `Domains::DomainRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::HeadDomainNumber` (r:1 w:0)
	/// Proof: `Domains::HeadDomainNumber` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::ExecutionInbox` (r:2 w:0)
	/// Proof: `Domains::ExecutionInbox` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainRuntimeUpgradeRecords` (r:1 w:0)
	/// Proof: `Domains::DomainRuntimeUpgradeRecords` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::HeadReceiptNumber` (r:1 w:0)
	/// Proof: `Domains::HeadReceiptNumber` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `RuntimeConfigs::EnableDynamicCostOfStorage` (r:1 w:0)
	/// Proof: `RuntimeConfigs::EnableDynamicCostOfStorage` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `TransactionFees::CollectedBlockFees` (r:1 w:1)
	/// Proof: `TransactionFees::CollectedBlockFees` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::FrozenDomains` (r:1 w:0)
	/// Proof: `Domains::FrozenDomains` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::Operators` (r:1 w:0)
	/// Proof: `Domains::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LatestSubmittedER` (r:1 w:0)
	/// Proof: `Domains::LatestSubmittedER` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::OperatorHighestSlot` (r:1 w:0)
	/// Proof: `Domains::OperatorHighestSlot` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::OperatorBundleSlot` (r:1 w:0)
	/// Proof: `Domains::OperatorBundleSlot` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LastEpochStakingDistribution` (r:1 w:0)
	/// Proof: `Domains::LastEpochStakingDistribution` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainStakingSummary` (r:1 w:0)
	/// Proof: `Domains::DomainStakingSummary` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Subspace::BlockSlots` (r:1 w:0)
	/// Proof: `Subspace::BlockSlots` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::BlockHash` (r:1 w:0)
	/// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Domains::NewAddedHeadReceipt` (r:1 w:0)
	/// Proof: `Domains::NewAddedHeadReceipt` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LatestConfirmedDomainExecutionReceipt` (r:1 w:0)
	/// Proof: `Domains::LatestConfirmedDomainExecutionReceipt` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::ConsensusBlockHash` (r:1 w:0)
	/// Proof: `Domains::ConsensusBlockHash` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::BlockTree` (r:1 w:0)
	/// Proof: `Domains::BlockTree` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn validate_submit_bundle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1437`
		//  Estimated: `7377`
		// Minimum execution time: 519_000_000 picoseconds.
		Weight::from_parts(519_000_000, 0)
			.saturating_add(Weight::from_parts(0, 7377))
			.saturating_add(T::DbWeight::get().reads(23))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Domains::DomainRegistry` (r:1 w:0)
	/// Proof: `Domains::DomainRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::HeadDomainNumber` (r:1 w:0)
	/// Proof: `Domains::HeadDomainNumber` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::ExecutionInbox` (r:2 w:0)
	/// Proof: `Domains::ExecutionInbox` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainRuntimeUpgradeRecords` (r:1 w:0)
	/// Proof: `Domains::DomainRuntimeUpgradeRecords` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::HeadReceiptNumber` (r:1 w:0)
	/// Proof: `Domains::HeadReceiptNumber` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `RuntimeConfigs::EnableDynamicCostOfStorage` (r:1 w:0)
	/// Proof: `RuntimeConfigs::EnableDynamicCostOfStorage` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `TransactionFees::CollectedBlockFees` (r:1 w:1)
	/// Proof: `TransactionFees::CollectedBlockFees` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::PreviousBundleAndExecutionReceiptVersions` (r:1 w:0)
	/// Proof: `Domains::PreviousBundleAndExecutionReceiptVersions` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::FrozenDomains` (r:1 w:0)
	/// Proof: `Domains::FrozenDomains` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::Operators` (r:1 w:0)
	/// Proof: `Domains::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LatestSubmittedER` (r:1 w:0)
	/// Proof: `Domains::LatestSubmittedER` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::OperatorHighestSlot` (r:1 w:0)
	/// Proof: `Domains::OperatorHighestSlot` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::OperatorBundleSlot` (r:1 w:0)
	/// Proof: `Domains::OperatorBundleSlot` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LastEpochStakingDistribution` (r:1 w:0)
	/// Proof: `Domains::LastEpochStakingDistribution` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainStakingSummary` (r:1 w:0)
	/// Proof: `Domains::DomainStakingSummary` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Subspace::BlockSlots` (r:1 w:0)
	/// Proof: `Subspace::BlockSlots` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::BlockHash` (r:1 w:0)
	/// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `Domains::NewAddedHeadReceipt` (r:1 w:0)
	/// Proof: `Domains::NewAddedHeadReceipt` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LatestConfirmedDomainExecutionReceipt` (r:1 w:0)
	/// Proof: `Domains::LatestConfirmedDomainExecutionReceipt` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::ConsensusBlockHash` (r:1 w:0)
	/// Proof: `Domains::ConsensusBlockHash` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::BlockTree` (r:1 w:0)
	/// Proof: `Domains::BlockTree` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn validate_singleton_receipt() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1467`
		//  Estimated: `7407`
		// Minimum execution time: 511_000_000 picoseconds.
		Weight::from_parts(511_000_000, 0)
			.saturating_add(Weight::from_parts(0, 7407))
			.saturating_add(T::DbWeight::get().reads(23))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Domains::BlockTreeNodes` (r:2 w:0)
	/// Proof: `Domains::BlockTreeNodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::HeadReceiptNumber` (r:1 w:0)
	/// Proof: `Domains::HeadReceiptNumber` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainRegistry` (r:1 w:0)
	/// Proof: `Domains::DomainRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::RuntimeRegistry` (r:1 w:0)
	/// Proof: `Domains::RuntimeRegistry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LatestConfirmedDomainExecutionReceipt` (r:1 w:0)
	/// Proof: `Domains::LatestConfirmedDomainExecutionReceipt` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn fraud_proof_pre_check() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2483106`
		//  Estimated: `2489046`
		// Minimum execution time: 972_000_000 picoseconds.
		Weight::from_parts(972_000_000, 0)
			.saturating_add(Weight::from_parts(0, 2489046))
			.saturating_add(T::DbWeight::get().reads(6))
	}
	/// Storage: `Domains::Operators` (r:1 w:1)
	/// Proof: `Domains::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LatestSubmittedER` (r:1 w:0)
	/// Proof: `Domains::LatestSubmittedER` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainStakingSummary` (r:1 w:1)
	/// Proof: `Domains::DomainStakingSummary` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DeactivatedOperators` (r:1 w:1)
	/// Proof: `Domains::DeactivatedOperators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn deactivate_operator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `631`
		//  Estimated: `4096`
		// Minimum execution time: 34_000_000 picoseconds.
		Weight::from_parts(34_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4096))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Domains::Operators` (r:1 w:1)
	/// Proof: `Domains::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LatestSubmittedER` (r:1 w:0)
	/// Proof: `Domains::LatestSubmittedER` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainStakingSummary` (r:1 w:1)
	/// Proof: `Domains::DomainStakingSummary` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DeactivatedOperators` (r:1 w:1)
	/// Proof: `Domains::DeactivatedOperators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn reactivate_operator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `601`
		//  Estimated: `4066`
		// Minimum execution time: 30_000_000 picoseconds.
		Weight::from_parts(30_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4066))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Domains::OperatorIdOwner` (r:1 w:0)
	/// Proof: `Domains::OperatorIdOwner` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::Operators` (r:1 w:1)
	/// Proof: `Domains::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LatestSubmittedER` (r:1 w:0)
	/// Proof: `Domains::LatestSubmittedER` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainStakingSummary` (r:1 w:1)
	/// Proof: `Domains::DomainStakingSummary` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::HeadDomainNumber` (r:1 w:0)
	/// Proof: `Domains::HeadDomainNumber` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `RuntimeConfigs::StakingWithdrawalPeriod` (r:1 w:0)
	/// Proof: `RuntimeConfigs::StakingWithdrawalPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Domains::DeactivatedOperators` (r:1 w:1)
	/// Proof: `Domains::DeactivatedOperators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DeregisteredOperators` (r:1 w:1)
	/// Proof: `Domains::DeregisteredOperators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn deregister_deactivated_operator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `731`
		//  Estimated: `4196`
		// Minimum execution time: 37_000_000 picoseconds.
		Weight::from_parts(37_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4196))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Domains::Operators` (r:1 w:1)
	/// Proof: `Domains::Operators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::LatestSubmittedER` (r:1 w:0)
	/// Proof: `Domains::LatestSubmittedER` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::PendingStakingOperationCount` (r:1 w:1)
	/// Proof: `Domains::PendingStakingOperationCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DomainStakingSummary` (r:1 w:0)
	/// Proof: `Domains::DomainStakingSummary` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::Deposits` (r:1 w:1)
	/// Proof: `Domains::Deposits` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::OperatorEpochSharePrice` (r:1 w:0)
	/// Proof: `Domains::OperatorEpochSharePrice` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::Withdrawals` (r:1 w:1)
	/// Proof: `Domains::Withdrawals` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::DeactivatedOperators` (r:1 w:1)
	/// Proof: `Domains::DeactivatedOperators` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Domains::OperatorIdOwner` (r:1 w:0)
	/// Proof: `Domains::OperatorIdOwner` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Holds` (r:1 w:1)
	/// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `Domains::HeadDomainNumber` (r:1 w:0)
	/// Proof: `Domains::HeadDomainNumber` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `RuntimeConfigs::StakingWithdrawalPeriod` (r:1 w:0)
	/// Proof: `RuntimeConfigs::StakingWithdrawalPeriod` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn withdraw_stake_from_deactivated_operator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1443`
		//  Estimated: `6196`
		// Minimum execution time: 106_000_000 picoseconds.
		Weight::from_parts(106_000_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(14))
			.saturating_add(T::DbWeight::get().writes(8))
	}
}
