
//! Autogenerated weights for pallet_domains
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-06-09, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `local`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/subspace-node
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_domains
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./crates/pallet-domains/src/weights.rs
// --template
// ./frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_domains.
pub trait WeightInfo {
	fn submit_system_bundle() -> Weight;
	fn submit_core_bundle() -> Weight;
	fn submit_system_domain_invalid_state_transition_proof() -> Weight;
}

/// Weights for pallet_domains using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: Settlement OldestReceiptNumber (r:1 w:1)
	/// Proof Skipped: Settlement OldestReceiptNumber (max_values: None, max_size: None, mode: Measured)
	/// Storage: Settlement HeadReceiptNumber (r:1 w:1)
	/// Proof Skipped: Settlement HeadReceiptNumber (max_values: None, max_size: None, mode: Measured)
	/// Storage: Settlement Receipts (r:1 w:2)
	/// Proof Skipped: Settlement Receipts (max_values: None, max_size: None, mode: Measured)
	/// Storage: Settlement ReceiptVotes (r:3 w:2)
	/// Proof Skipped: Settlement ReceiptVotes (max_values: None, max_size: None, mode: Measured)
	/// Storage: Settlement PrimaryBlockHash (r:1 w:1)
	/// Proof Skipped: Settlement PrimaryBlockHash (max_values: None, max_size: None, mode: Measured)
	/// Storage: Domains SuccessfulBundles (r:1 w:1)
	/// Proof Skipped: Domains SuccessfulBundles (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Settlement StateRoots (r:0 w:1)
	/// Proof Skipped: Settlement StateRoots (max_values: None, max_size: None, mode: Measured)
	fn submit_system_bundle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4063`
		//  Estimated: `52201`
		// Minimum execution time: 128_000_000 picoseconds.
		Weight::from_parts(133_000_000, 52201)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(9_u64))
	}
	/// Storage: Domains SuccessfulBundles (r:1 w:1)
	/// Proof Skipped: Domains SuccessfulBundles (max_values: Some(1), max_size: None, mode: Measured)
	fn submit_core_bundle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1491`
		// Minimum execution time: 13_000_000 picoseconds.
		Weight::from_parts(14_000_000, 1491)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Settlement HeadReceiptNumber (r:1 w:1)
	/// Proof Skipped: Settlement HeadReceiptNumber (max_values: None, max_size: None, mode: Measured)
	/// Storage: Settlement PrimaryBlockHash (r:256 w:0)
	/// Proof Skipped: Settlement PrimaryBlockHash (max_values: None, max_size: None, mode: Measured)
	/// Storage: Settlement ReceiptVotes (r:510 w:255)
	/// Proof Skipped: Settlement ReceiptVotes (max_values: None, max_size: None, mode: Measured)
	/// Storage: Settlement Receipts (r:255 w:255)
	/// Proof Skipped: Settlement Receipts (max_values: None, max_size: None, mode: Measured)
	/// Storage: Settlement StateRoots (r:100 w:255)
	/// Proof Skipped: Settlement StateRoots (max_values: None, max_size: None, mode: Measured)
	/// Storage: Settlement SuccessfulFraudProofs (r:1 w:1)
	/// Proof Skipped: Settlement SuccessfulFraudProofs (max_values: Some(1), max_size: None, mode: Measured)
	fn submit_system_domain_invalid_state_transition_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `100355`
		//  Estimated: `3385515`
		// Minimum execution time: 7_486_000_000 picoseconds.
		Weight::from_parts(7_972_000_000, 3385515)
			.saturating_add(T::DbWeight::get().reads(1123_u64))
			.saturating_add(T::DbWeight::get().writes(767_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: Settlement OldestReceiptNumber (r:1 w:1)
	/// Proof Skipped: Settlement OldestReceiptNumber (max_values: None, max_size: None, mode: Measured)
	/// Storage: Settlement HeadReceiptNumber (r:1 w:1)
	/// Proof Skipped: Settlement HeadReceiptNumber (max_values: None, max_size: None, mode: Measured)
	/// Storage: Settlement Receipts (r:1 w:2)
	/// Proof Skipped: Settlement Receipts (max_values: None, max_size: None, mode: Measured)
	/// Storage: Settlement ReceiptVotes (r:3 w:2)
	/// Proof Skipped: Settlement ReceiptVotes (max_values: None, max_size: None, mode: Measured)
	/// Storage: Settlement PrimaryBlockHash (r:1 w:1)
	/// Proof Skipped: Settlement PrimaryBlockHash (max_values: None, max_size: None, mode: Measured)
	/// Storage: Domains SuccessfulBundles (r:1 w:1)
	/// Proof Skipped: Domains SuccessfulBundles (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: Settlement StateRoots (r:0 w:1)
	/// Proof Skipped: Settlement StateRoots (max_values: None, max_size: None, mode: Measured)
	fn submit_system_bundle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4063`
		//  Estimated: `52201`
		// Minimum execution time: 128_000_000 picoseconds.
		Weight::from_parts(133_000_000, 52201)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(9_u64))
	}
	/// Storage: Domains SuccessfulBundles (r:1 w:1)
	/// Proof Skipped: Domains SuccessfulBundles (max_values: Some(1), max_size: None, mode: Measured)
	fn submit_core_bundle() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1491`
		// Minimum execution time: 13_000_000 picoseconds.
		Weight::from_parts(14_000_000, 1491)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Settlement HeadReceiptNumber (r:1 w:1)
	/// Proof Skipped: Settlement HeadReceiptNumber (max_values: None, max_size: None, mode: Measured)
	/// Storage: Settlement PrimaryBlockHash (r:256 w:0)
	/// Proof Skipped: Settlement PrimaryBlockHash (max_values: None, max_size: None, mode: Measured)
	/// Storage: Settlement ReceiptVotes (r:510 w:255)
	/// Proof Skipped: Settlement ReceiptVotes (max_values: None, max_size: None, mode: Measured)
	/// Storage: Settlement Receipts (r:255 w:255)
	/// Proof Skipped: Settlement Receipts (max_values: None, max_size: None, mode: Measured)
	/// Storage: Settlement StateRoots (r:100 w:255)
	/// Proof Skipped: Settlement StateRoots (max_values: None, max_size: None, mode: Measured)
	/// Storage: Settlement SuccessfulFraudProofs (r:1 w:1)
	/// Proof Skipped: Settlement SuccessfulFraudProofs (max_values: Some(1), max_size: None, mode: Measured)
	fn submit_system_domain_invalid_state_transition_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `100355`
		//  Estimated: `3385515`
		// Minimum execution time: 7_486_000_000 picoseconds.
		Weight::from_parts(7_972_000_000, 3385515)
			.saturating_add(RocksDbWeight::get().reads(1123_u64))
			.saturating_add(RocksDbWeight::get().writes(767_u64))
	}
}
